
package QuanLyBanHang;

import QuanLyBanHangDao.CTHD_Dao;
import QuanLyBanHangDao.NhanVienDao;
import QuanLyBanHangHelper.OracleJDBCConnection;
import QuanLyBanHangModel.CTHD;
import QuanLyBanHangModel.HoaDon;
import QuanLyBanHangModel.NhanVien;
import QuanLyBanHangDao.HoaDon_Dao;
import TrangChu.home;
import java.awt.BufferCapabilities;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

/**
 *
 * @author Nguyen Linh
 */
public class BanHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    Long Tong;
    private home home;
    private ImageIcon icon;	
    public BanHang(){}
    public BanHang(home home) {
       this.home=home;
        
        initComponents();
        getContentPane().setBackground(Color.white); 
        Connect();
        //NhanVien_Load();
    }
    public JPanel getJPanelNV()
    {
        return jPanelNV;
    }
    
      public void Connect(){ //ket noi csdl
        try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        System.out.print("ket noi thanh cong");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            
           conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","QuanLyBanHang", "qlbh");
        
        } catch (SQLException ex) {
            //Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      
    
    
    public void CTHD_Load(){
         CTHD cthd = new CTHD();
        try {
            ps = conn.prepareStatement("SELECT * FROM CTHD WHERE SOHD = ? ");
            ps.setInt(1, Integer.parseInt(txtSoHD.getText()));
            rs = ps.executeQuery();
           
            
            DefaultTableModel model = (DefaultTableModel) listCTHD.getModel();
            model.setRowCount(0);
            
            while (rs.next()){
                Vector v1 = new Vector();
                    v1.add(rs.getString("masp"));
                    v1.add(rs.getInt("sohd"));
                    v1.add(rs.getInt("sl"));
                    
             // }
                model.addRow(v1);
               //listNV.setModel(model);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    public void LamMoi(){
        txtMaKH.setText("");
        txtSoHD.setText("");
        jDNgHD.setDate(null);
        txtMaNV.setText("");
        txtMaSP.setText("");
        txtSoLuong.setText("");
  }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNV = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBTimKiem = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jBThemMoi = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBXoa = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBCapNhat = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jBLamMoi = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jDNgHD = new com.toedter.calendar.JDateChooser();
        bt_Them = new javax.swing.JButton();
        Bt_HoanTat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCTHD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNV.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        jBTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jBTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/find.png"))); // NOI18N
        jBTimKiem.setText("Tìm kiếm");
        jBTimKiem.setFocusable(false);
        jBTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTimKiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTimKiemActionPerformed(evt);
            }
        });
        jToolBar1.add(jBTimKiem);
        jToolBar1.add(jSeparator6);

        jBThemMoi.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jBThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/insert.png"))); // NOI18N
        jBThemMoi.setText("Thêm mới");
        jBThemMoi.setFocusable(false);
        jBThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThemMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(jBThemMoi);
        jToolBar1.add(jSeparator3);

        jBXoa.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jBXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/delete.png"))); // NOI18N
        jBXoa.setText("    Xóa    ");
        jBXoa.setFocusable(false);
        jBXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });
        jToolBar1.add(jBXoa);
        jToolBar1.add(jSeparator4);

        jBCapNhat.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jBCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/edit.png"))); // NOI18N
        jBCapNhat.setText("Cập nhật");
        jBCapNhat.setFocusable(false);
        jBCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCapNhatActionPerformed(evt);
            }
        });
        jToolBar1.add(jBCapNhat);
        jToolBar1.add(jSeparator5);

        jBLamMoi.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jBLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/refresh.png"))); // NOI18N
        jBLamMoi.setText("Làm mới");
        jBLamMoi.setFocusable(false);
        jBLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBLamMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLamMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(jBLamMoi);
        jToolBar1.add(jSeparator7);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Số hoá đơn");

        txtSoHD.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Ngày hoá đơn");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Mã khách hàng");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Mã nhân viên");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Mã SP");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Số Lượng");

        bt_Them.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bt_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/insert.png"))); // NOI18N
        bt_Them.setText("Thêm CTHD");
        bt_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ThemActionPerformed(evt);
            }
        });

        Bt_HoanTat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Bt_HoanTat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcon/complete.png"))); // NOI18N
        Bt_HoanTat.setText("Hoàn Tất");
        Bt_HoanTat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_HoanTatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_HoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoHD)
                            .addComponent(txtMaKH)
                            .addComponent(txtMaNV)
                            .addComponent(txtMaSP)
                            .addComponent(txtSoLuong)
                            .addComponent(jDNgHD, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoHD, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jDNgHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bt_HoanTat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        listCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MASP", "SOHD", "Số lượng"
            }
        ));
        listCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCTHDMouseClicked(evt);
            }
        });
        listCTHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listCTHDKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listCTHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelNVLayout = new javax.swing.GroupLayout(jPanelNV);
        jPanelNV.setLayout(jPanelNVLayout);
        jPanelNVLayout.setHorizontalGroup(
            jPanelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNVLayout.createSequentialGroup()
                .addGroup(jPanelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNVLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelNVLayout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelNVLayout.setVerticalGroup(
            jPanelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNVLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTimKiemActionPerformed

    }//GEN-LAST:event_jBTimKiemActionPerformed

    private void jBThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThemMoiActionPerformed
        // TODO add your handling code here:
        try{
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","QuanLyBanHang", "qlbh");
        String strCall = "{?=call TimSoHD}";
        CallableStatement call = conn.prepareCall(strCall);
        call.registerOutParameter(1,java.sql.Types.NUMERIC);
        call.executeUpdate();; 
        int rss= call.getInt(1);
//        int rs = call;
        System.out.println(rss);
        txtSoHD.setText( String.valueOf(rss));
        }catch(SQLException ex){
            //executeUpdate nó trả về số dòng thay đổi đúng hem
        }
        
        
      
      
      
    }//GEN-LAST:event_jBThemMoiActionPerformed

    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
   
    }//GEN-LAST:event_jBXoaActionPerformed

    private void jBCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCapNhatActionPerformed
      
    }//GEN-LAST:event_jBCapNhatActionPerformed

    private void jBLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLamMoiActionPerformed
        // TODO add your handling code here:
        LamMoi();
    }//GEN-LAST:event_jBLamMoiActionPerformed

    private void listCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCTHDMouseClicked
        // TODO add your handling code here:
        /*
        LamMoi();
        int selectedIndex = listNV.getSelectedRow();
        listNV.setColumnSelectionInterval(0,7);
        txtMaNV.setText(listNV.getValueAt(selectedIndex, 0).toString());
        txtHoTen.setText(listNV.getValueAt(selectedIndex, 1).toString());

        jDNgVL.setDate((Date) listNV.getValueAt(selectedIndex, 2));
        // gioi tinh
        String sex = listNV.getValueAt(selectedIndex, 3).toString();
        if (sex.equals("Nu")){
            gtNu.setSelected(true);
            gtNam.setSelected(false);
        } else if (sex.equals("Nam")){ gtNam.setSelected(true);
        gtNu.setSelected(false);
        }
        
        txtCMND.setText(listNV.getValueAt(selectedIndex, 4).toString());
        txtDiaChi.setText(listNV.getValueAt(selectedIndex, 5).toString());
        txtSDT.setText(listNV.getValueAt(selectedIndex, 6).toString());
        txtUserID.setText(listNV.getValueAt(selectedIndex, 7).toString());
        txtMatKhau.setText(listNV.getValueAt(selectedIndex, 8).toString());
        TxtLoaiNhanVien.setText(listNV.getValueAt(selectedIndex, 9).toString());
        */
    }//GEN-LAST:event_listCTHDMouseClicked

    private void listCTHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listCTHDKeyReleased
        // TODO add your handling code here:
//        LamMoi();
//        
//        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
//        int selectedIndex = listNV.getSelectedRow();
//        listNV.setColumnSelectionInterval(0,7);
//        txtMaNV.setText(listNV.getValueAt(selectedIndex, 0).toString());
//        txtHoTen.setText(listNV.getValueAt(selectedIndex, 1).toString());
//        jDNgVL.setDate((Date) listNV.getValueAt(selectedIndex, 2));
//       
//        // gioi tinh
//        
//        String sex = listNV.getValueAt(selectedIndex, 3).toString();
//        if (sex.equals("Nu")){
//            gtNu.setSelected(true);
//            gtNam.setSelected(false);
//        } else if (sex.equals("Nam")){ gtNam.setSelected(true);
//        gtNu.setSelected(false);
//        }
//        
//        txtCMND.setText(listNV.getValueAt(selectedIndex, 4).toString());
//        txtDiaChi.setText(listNV.getValueAt(selectedIndex, 5).toString());
//        txtSDT.setText(listNV.getValueAt(selectedIndex, 6).toString());
//        txtUserID.setText(listNV.getValueAt(selectedIndex, 7).toString());
//        txtMatKhau.setText(listNV.getValueAt(selectedIndex, 8).toString());
//        TxtLoaiNhanVien.setText(listNV.getValueAt(selectedIndex, 9).toString());
//        Date date = null;
//        try {
//            date = new SimpleDateFormat("yyyy-MM-dd").parse((String)listNV.getValueAt(selectedIndex, 2));
//        } catch (ParseException ex) {
//            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        jDNgVL.setDate(date);
//           
//       }
    }//GEN-LAST:event_listCTHDKeyReleased

    private void bt_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ThemActionPerformed
        // TODO add your handling code here:
        //HoaDon hd = new HoaDon();
         
          try{
         conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","QuanLyBanHang", "qlbh");
        String strCall = "{?=call Check_Sohd(?)}";
        CallableStatement call = conn.prepareCall(strCall);
        call.registerOutParameter(1,java.sql.Types.NUMERIC);
        call.setInt(2,Integer.parseInt(txtSoHD.getText()));
        call.executeUpdate();; 
        int rss= call.getInt(1);
//        int rs = call;
        //System.out.println(rss);
        if(rss==0){
            /*Them 1 hoa don ao*/
              try{  
        HoaDon hd = new HoaDon();
        hd.setSoHD(Integer.parseInt(txtSoHD.getText()));
        //hd.set(txtHoTen.getText());
        //Chuyen doi java.util.Date sang java.sql.Date
        if(jDNgHD.getDate() != null ){
        java.util.Date utilStartDate = jDNgHD.getDate();
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        hd.setNGHD(sqlStartDate);
    }
        hd.setMaKH(txtMaKH.getText());
        hd.setMaNV(txtMaNV.getText());
        hd.setTriGia(0);
        HoaDon_Dao dao = new HoaDon_Dao();
        dao.insert(hd);    
        
        //JOptionPane.showMessageDialog(this, "Nhân viên được thêm vào thành công!");
      } catch (Exception e){
          JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
      }   
        }
        //txtSoHD.setText( String.valueOf(rss));
        }catch(SQLException ex){
            //executeUpdate nó trả về số dòng thay đổi đúng hem
        }
        
        

        
        try{  
        CTHD cthd = new CTHD();
        cthd.setSoHD(Integer.parseInt(txtSoHD.getText()));
        cthd.setMaSP(txtMaSP.getText());
        cthd.setSL(Integer.parseInt(txtSoLuong.getText()));
       
            
           CTHD_Dao dao = new CTHD_Dao();
           dao.insert(cthd);    
        JOptionPane.showMessageDialog(this, "Món hàng được thêm vào thành công!");
      } catch (Exception e){
          JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
      }
      CTHD_Load();
      
      txtMaSP.setText("");
      txtSoLuong.setText("");
      
    }//GEN-LAST:event_bt_ThemActionPerformed

    private void Bt_HoanTatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_HoanTatActionPerformed
        // TODO add your handling code here:
        HoaDon_Dao hd = new HoaDon_Dao();
        home.setIndex(0);
        dispose();
        //jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_Bt_HoanTatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
  
                new BanHang().setVisible(true);
            }
        });
    }
    
    class ImagePanel extends JPanel {

  private Image img;

  public ImagePanel(String img) {
    this(new ImageIcon(img).getImage());
  }

  public ImagePanel(Image img) {
    this.img = img;
    Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
    setPreferredSize(size);
    setMinimumSize(size);
    setMaximumSize(size);
    setSize(size);
    setLayout(null);
  }

  public void paintComponent(Graphics g) {
    g.drawImage(img, 0, 0, null);
  }

}  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_HoanTat;
    private javax.swing.JButton bt_Them;
    private javax.swing.JButton jBCapNhat;
    private javax.swing.JButton jBLamMoi;
    private javax.swing.JButton jBThemMoi;
    private javax.swing.JButton jBTimKiem;
    private javax.swing.JButton jBXoa;
    private com.toedter.calendar.JDateChooser jDNgHD;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelNV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable listCTHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoHD;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
