/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyBanHang;

import QuanLyBanHangHelper.OracleJDBCConnection;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PC
 */
public class BaoCao extends javax.swing.JFrame {

    /**
     * Creates new form BaoCaoDoanhThu
     */
    public BaoCao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_baocao = new javax.swing.JPanel();
        box_thongkenam = new javax.swing.JComboBox<>();
        box_thongkethang = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Top5_BanDuoc = new javax.swing.JPanel();
        Top5BanDuoc = new javax.swing.JLabel();
        DoanhThuTheoNam = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        box_thongkenam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_thongkenam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100" }));

        box_thongkethang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_thongkethang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jPanel10.setBackground(new java.awt.Color(255, 204, 102));

        jLabel19.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Thống kê");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(19, 19, 19))
        );

        Top5_BanDuoc.setBackground(new java.awt.Color(255, 204, 102));
        Top5_BanDuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Top5_BanDuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Top5_BanDuocMouseEntered(evt);
            }
        });

        Top5BanDuoc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Top5BanDuoc.setForeground(new java.awt.Color(255, 102, 51));
        Top5BanDuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top5BanDuoc.setText("Thống kê sản phẩm bán được theo tháng ");

        javax.swing.GroupLayout Top5_BanDuocLayout = new javax.swing.GroupLayout(Top5_BanDuoc);
        Top5_BanDuoc.setLayout(Top5_BanDuocLayout);
        Top5_BanDuocLayout.setHorizontalGroup(
            Top5_BanDuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Top5_BanDuocLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Top5BanDuoc)
                .addGap(21, 21, 21))
        );
        Top5_BanDuocLayout.setVerticalGroup(
            Top5_BanDuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Top5_BanDuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Top5BanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DoanhThuTheoNam.setBackground(new java.awt.Color(255, 204, 102));
        DoanhThuTheoNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoanhThuTheoNamMouseClicked(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 102, 51));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Doanh Thu Theo Năm");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DoanhThuTheoNamLayout = new javax.swing.GroupLayout(DoanhThuTheoNam);
        DoanhThuTheoNam.setLayout(DoanhThuTheoNamLayout);
        DoanhThuTheoNamLayout.setHorizontalGroup(
            DoanhThuTheoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoanhThuTheoNamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        DoanhThuTheoNamLayout.setVerticalGroup(
            DoanhThuTheoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoanhThuTheoNamLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addGap(23, 23, 23))
        );

        jLabel62.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel62.setText("Tháng:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Năm:");

        javax.swing.GroupLayout panel_baocaoLayout = new javax.swing.GroupLayout(panel_baocao);
        panel_baocao.setLayout(panel_baocaoLayout);
        panel_baocaoLayout.setHorizontalGroup(
            panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_baocaoLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel62)
                .addGap(29, 29, 29)
                .addComponent(box_thongkethang, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(box_thongkenam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_baocaoLayout.createSequentialGroup()
                .addGroup(panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_baocaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DoanhThuTheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Top5_BanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_baocaoLayout.setVerticalGroup(
            panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_baocaoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(box_thongkethang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(box_thongkenam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoanhThuTheoNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top5_BanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_baocao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_baocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Top5_BanDuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top5_BanDuocMouseClicked
         String thang = box_thongkethang.getSelectedItem().toString();
        String nam = box_thongkenam.getSelectedItem().toString();
        HashMap hashmap = new HashMap();
        hashmap.put("Thang", thang);
        hashmap.put("Nam", nam);
        try {
            Connection con = OracleJDBCConnection.getJDBCConnection();
            String dir = "E:\\UIT\\Nam2\\LapTrinhJava\\DoAn\\QuanLiBanHang_BanHoanChinh\\QuanLiBanHang_08\\src\\report\\thang_top5nhieunhat.jrxml";
            JasperDesign jd = JRXmlLoader.load(dir);
            JasperReport jr = JasperCompileManager.compileReport(dir);
            JasperPrint jp = JasperFillManager.fillReport(jr, hashmap,con);
            JasperViewer.viewReport(jp);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_Top5_BanDuocMouseClicked

    private void Top5_BanDuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top5_BanDuocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Top5_BanDuocMouseEntered

    private void DoanhThuTheoNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoanhThuTheoNamMouseClicked

        int nam = Integer.parseInt(box_thongkenam.getSelectedItem().toString());
        HashMap hashmap = new HashMap();
        hashmap.put("nam", nam);
        try {
            Connection con = OracleJDBCConnection.getJDBCConnection();
            String dir = "E:\\UIT\\Nam2\\LapTrinhJava\\DoAn\\QuanLiBanHang_BanHoanChinh\\QuanLiBanHang_08\\src\\report\\ThongKeDoanhThu.jrxml";
            JasperDesign jd = JRXmlLoader.load(dir);
            JasperReport jr = JasperCompileManager.compileReport(dir);
            JasperPrint jp = JasperFillManager.fillReport(jr, hashmap,con);
            JasperViewer.viewReport(jp);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_DoanhThuTheoNamMouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel55MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoanhThuTheoNam;
    private javax.swing.JLabel Top5BanDuoc;
    private javax.swing.JPanel Top5_BanDuoc;
    private javax.swing.JComboBox<String> box_thongkenam;
    private javax.swing.JComboBox<String> box_thongkethang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel panel_baocao;
    // End of variables declaration//GEN-END:variables
}
